### ISSUE TITLE
Bug with webpack 5

### ISSUE THREAD

**Issue by ByJfMarie** [SoTrxII/marmiton-api#2]
Bonjour,

J’aurais une question à poser, j’essaie d’utiliser votre API Marmiton pour un projet sur vuejs3
![dsqdqsq](https://user-images.githubusercontent.com/43115731/134365389-dfff2505-f2e1-4552-a10c-c76ded0ec5de.png)
J’ai essayé de trouver des solutions sur internet mais je ne trouve rien et je ne trouve surtout pas le fichier ou ajouter le ‘resolve.fallback’

Je vous remercie par avance de votre réponse

**Comment by SoTrxII** [comment]
Bonjour,
Je pense que le problème vient du fait que certains modules de Nodejs sont utilisés dans la bibliothèque, et que ces modules ne sont pas disponibles pour le navigateur ; en tous cas c'est ce que je comprends de l'erreur de Webpack.

Je pense qu'il faut que vous importiez le polyfill pour zlib dans votre config Vue.

D'après [ce post ](https://stackoverflow.com/questions/50304066/webpack-config-missing-in-vuejs), il faudrait créer un fichier vue.config.js avec une section `configureWebpack`, dans cette section vous pourriez alors rajouter ce qu'il vous demande, c'est à dire : 

```js
{
  resolve: {
        fallback: { "zlib": require.resolve("browserify-zlib") }
  }
}  
```
Il vous faudra donc aussi installer le module browerify-zlib.

Dans tous les cas, je ne savais pas que Webpack  avait supprimé les polyfills automatiques. Si cela se confirme, je rajouterai un avertissement sur le readme. 

Bonne chance pour votre configuration !

**Comment by ByJfMarie** [comment]
Suite à vos informations, j'ai pu compiler après avoir add ce qu'il faut.
Il ne me reste juste un warning : 
![image](https://user-images.githubusercontent.com/43115731/134388179-d3db7bc7-020f-4249-b5c3-c7ba7aa3ccd8.png)

Par contre lors de l'appelle d'une requête j'ai des erreurs de permissions, avez vous une idée ? 
![image](https://user-images.githubusercontent.com/43115731/134388289-7752ed42-3463-4d17-964c-526a8714c5cd.png)

Merci pour vos réponses

**Comment by SoTrxII** [comment]
Le warning est dû au fait que le module [encoding](https://www.npmjs.com/package/encoding) est aussi demandé, il vous faudra peut être le polyfill également, comme pour zlib.

L'erreur lors de la requête est malheureusement normale. Le site marmiton (comme beaucoup d'autres) est protégé par les [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing). Le but de cette protection est d'éviter qu'un site web fasse appel aux ressources d'un autre, et c'est précisément ce qui est fait puisque vous utilisez votre site web local pour en appeler un autre (marmiton).

Mon conseil serait de relayer le requêtage de marmiton à votre backend plutôt que de le faire en frontend, quitte à exposer un petit serveur Web ou même une simple lamdba pour vos traitements.
