### ISSUE TITLE
Image non présente dans l'objet JSON

### ISSUE THREAD

**Issue by MaelStorm176** [SoTrxII/marmiton-api#4]
Bonjour, j'utilise ce package pour un projet scolaire. Il est vraiment top !

J'ai cru comprendre dans la doc que l'API pouvait nous fournir l'image de la recette :
![image](https://user-images.githubusercontent.com/57861637/178542133-dc9fe7c4-80ca-4a7d-8e50-9b5e535e651b.png)

Malheureusement je ne l'a retrouve pas dans l'objet JSON que renvoit l'API.
`{
      "name": "Quiche tatin",
      "rate": 4.7,
      "url": "https://www.marmiton.org/recettes/recette_quiche-tatin_14309.aspx",
      "ingredients": [
        "7 pommes de terre",
        "20 cl de crème fraîche",
        "150 g de gruyère râpé",
        "sel",
        "poivre",
        "8 fines tranches de lard",
        "3 oeufs entiers",
        "1 fromage de chèvre",
        "1 pâte feuilletée"
      ],
      "author": "Anonyme",
      "steps": [
        "Cuire les pommes de terre à la vapeur.\nPréchauffer le four à 200°C (thermostat 6-7).",
        "Tapisser le moule de tranches de lard.",
        "Mettre le râpé sur les tranches de lard. ",
        "Couper les pommes de terre en rondelles sur le râpé, puis le fromage de chèvre en tranches.",
        "Battre dans un bol la crème, les oeufs, le sel et poivre, verser sur la préparation.",
        "Mettre la pâte feuilletée dessus comme une tarte tatin et la piquer.",
        "Cuire pendant 30 min suivant le four."
      ],
      "description": "pomme de terre, crème fraîche, gruyère râpé, sel, poivre, lard, oeuf, fromage de chèvre, pâte feuilletée",
      "difficulty": 1,
      "budget": 1,
      "tags": [
        "Quiche tatin",
        "pomme de terre",
        "crème fraîche",
        "gruyère râpé",
        "sel",
        "poivre",
        "lard",
        "oeuf",
        "fromage de chèvre",
        "pâte feuilletée",
        "quiche Tatin",
        "très facile",
        "bon marché"
      ],
      "prepTime": 15,
      "totalTime": 45,
      "people": 6
    },`

La query : 
![image](https://user-images.githubusercontent.com/57861637/178542505-ec690cca-6104-4af5-b657-acee7759f4b5.png)

Aurait-il un mot clé précis à mettre dans la query pour avoir l'image de la recette ? 

Merci d'avance !

**Comment by SoTrxII** [comment]
Bonjour,
Il se trouve que l'attribut image était déclaré mais simplement non récupéré par le scrapper.
C'est corrigé dans la dernière version 2.3.0

Merci de l'avoir remarqué !
